### PR TITLE
Return a 503 header

### PR DESCRIPTION
**Pull request by benoitchantre**
Prevents search engines to index the content of the maintenance page.

### CODE REVIEW

**Comment by ethitter** [comment]
Thanks! This is a great start, but can be a bit simpler: WordPress provides the `status_header()` function for situations like this.

**Comment by benoitchantre** [comment]
Done. I have also changed the Retry-After value to set one hour instead of 10 minutes and I think the charset could be removed.

**Comment by joshbetz** [comment]
👍 This will also trigger `stale-while-error` content in page caches like Varnish, so users won't see the maintenance page unless there is no cached copy of the page.

**Comment by emrikol** [comment]
@ethitter @benchilcote @joshbetz What if we were to put that in a filter?

I've seen uses of the maintenance mode plugin for pre-launch splash pages and such where a 503 code might not be applicable.

Edit: Clarified what kind of "splash pages" and cc'd @joshbetz

**Comment by benoitchantre** [comment]
@emrikol I think a maintenance mode should always return a 503 by default.

For other usages than true maintenance, it would probably be easier for the user to add a template with a specific name to prevent the 503 code than to set a filter.
We could detect if that template exists and skip the 503 if needed. A filter could be added to set a custom file name for the template.

What do you think?

--

Edit: oops, I wasn't supposed to answer

**Comment by ethitter** [comment]
I tend to agree with @benoitchantre that the maintenance mode plugin should focus on providing maintenance mode alone. That said, @emrikol has seen more client use-cases for this plugin than I have, and if a filter will avoid clients' need to create similar functionality (and fight with Varnish, etc), I'm okay with it.

If we do provide a filter on the status code, we'll need one around the sending of the `Retry-After` header too, at which point, we should probably offer a filter on the duration as well.

**Comment by emrikol** [comment]
@benoitchantre What if we put the HTTP Header functionality inside `template-maintenance-mode.php`? That way the _default_ template will have that, but if someone wants to do something custom, they can have whatever headers they want and have the template to go by.

Also, after discussing it with some colleagues, we'll at least need a filter on the `status_header()` status code.  

As it stands right now, our internal tooling and monitoring will set off all sorts of alarms if a `50x` status is returned on a site.  With a filter we can check and modify that internally to make sure we don't alert for any down sites that aren't truly down (just in maintenance mode).

**Comment by benoitchantre** [comment]
@emrikol It is a more risky option: if the user creates a custom template, he will probably forget to set the status code and this can have a negative impact on SEO.

> Outages that are not clearly marked as such can negatively affect a site’s reputation.

> We encounter a lot of problems with sites that return 200 (OK) result codes for server errors, downtime, bandwidth-overruns or for temporary placeholder pages (“Under Construction”). The 503 HTTP result code is the webmaster’s solution of choice for all these situations.

Source: [How to deal with planned site downtime](https://webmasters.googleblog.com/2011/01/how-to-deal-with-planned-site-downtime.html) - Official Google Webmaster Central Blog.

Is there a way to bypass your alarms or to delay them?
Maybe with a custom HTTP request header?

Edit: added another quote

**Comment by philipjohn** [comment]
@emrikol Rather than change the plugin behaviour to not make our alerting go crazy, could we add a header that would tell us the 503 is generated by this plugin, and have our alerting ignore it? I'm not knowledgeable enough on the alerting to know if that's feasible.

**Comment by joshbetz** [comment]
Or we can just disable monitoring while the plugin is active.

**Comment by benoitchantre** [comment]
Here's a proposal following your comments.
Should we support an http-date as value for Retry-After as described in the spec?

```php
// Prevents search engines to index the content of the maintenance page.
$respond_503 = apply_filters( 'vip_maintenance_mode_respond_503', true );

// Number of seconds or between retries. Honored by search engines.
$retry_after = apply_filters( 'vip_maintenance_mode_retry_after', 3600 );

if ( true === $respond_503 ) {
	status_header( 503 );
	header( 'Retry-After: ' . absint( $retry_after ) );
}
```

**Comment by ethitter** [comment]
Disabling monitoring will be easier than changing how the monitoring works. We don't have an effective way of passing "metadata" to the monitoring system for it to change its behaviour, but we can temporarily exclude a site from our checks.

**Comment by ethitter** [comment]
> Should we support an http-date as value for Retry-After as described in the spec?

We should, because if we don't, someone will try to set a date and then open an issue. 😄

**Comment by benoitchantre** [comment]
The latest commit adds two filters and supports http-date for Retry-After.
Let me know if something needs to be improved.

**Comment by benoitchantre** [comment]
*[Closing down for a day](https://webmasters.googleblog.com/2017/02/closing-down-for-day.html)* : a fresh article from Google Webmaster Central Blog published yesterday.

> If you need to block the whole site from users, be it with a "temporarily unavailable" message, informational page, or popup, the server should return a 503 HTTP result code ("Service Unavailable"). The 503 result code makes sure that Google doesn't index the temporary content that's shown to users. Without the 503 result code, the interstitial would be indexed as your website's content.

> Googlebot will retry pages that return 503 for up to about a week, before treating it as a permanent error that can result in those pages being dropped from the search results. You can also include a "Retry after" header to indicate how long the site will be unavailable. Blocking a site for longer than a week can have negative effects on the site's search results regardless of the method that you use.

Based on that and your users knowledge, should they be:
- informed after the plugin activation?
- reminded after x days when a 503 is in place?
- other?

The readme is probably not enough to be safe.

**Comment by joshbetz** [comment]
I don't think we'd need to remind anyone. In the case that we serve 503 it is probably not enabled for more than an hour or two.

**Comment by philipjohn** [comment]
Looks like this code is good to go @benchilcote, thank you!

Can I ask you for one last thing? Let's make sure these new filters are properly documented inline with the [core documentation standards](https://make.wordpress.org/core/handbook/best-practices/inline-documentation-standards/php/#4-hooks-actions-and-filters).

**Comment by benoitchantre** [comment]
@philipjohn I think you mentioned someone else by error.
I'll update the inline documentation probably tonight (GMT +2).

**Comment by philipjohn** [comment]
Oops! Sorry about that!

**Comment by benoitchantre** [comment]
@philipjohn No problem, I did a similar error previously when I answered a question addressed to benchilcote.

**Comment by benoitchantre** [comment]
Looks good? I don't know if `@since` has to be added now.

```php
/**
 * Filters wether to respond with a 503 status code.
 *
 * The 503 status code prevents search engines to index the content of the maintenance page.
 *
 * @since 0.1.1
 *
 * @param bool $bool Whether to respond with a 503 status code. Default true.
 */
$respond_503 = apply_filters( 'vip_maintenance_mode_respond_503', true );
```

```php
/**
 * Filters the Retry-After value used to indicate how long the service is expected to be unavailable.
 *
 * @since 0.1.1
 *
 * @param int|string The delay in seconds or an http-date. Default to one hour.
 */
$retry_after = apply_filters( 'vip_maintenance_mode_retry_after', 3600 );

if ( is_int( $retry_after ) ) {
	header( 'Retry-After: ' . absint( $retry_after ) );
} elseif ( strtotime( $retry_after ) > time() ) {
	header( 'Retry-After: ' . gmdate( 'D, d M Y H:i:s T', strtotime( $retry_after ) ) );
}
```

**Comment by benoitchantre** [comment]
@philipjohn: ping :-)

**Review by philipjohn — APPROVED** [review]

**Comment by philipjohn** [comment]
Thanks @benoitchantre !

**Pull request merged**
